notifications:
  webhooks:
    - https://webhook.commit-email.info/
matrix:
  include:
    - name: "2.4"
      rvm: 2.4
    - name: "2.5"
      rvm: 2.5
    - name: "2.6"
      rvm: 2.6
    - name: "2.7"
      rvm: 2.7
    - name: "3.0"
      rvm: 3.0
    - name: "trunk"
      rvm: ruby-head
    - name: "gem"
      rvm: 2.7
      install:
        - rake install
      script:
        - mkdir -p tmp
        - cd tmp
        - cp -a ../test/ ./
        - ../run-test.rb
